"""add_embedding_timestamps_to_documents

Revision ID: 39f72c57c1b7
Revises: bee2be49ce3d
Create Date: 2026-09-29 19:37:23.729752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f72c57c1b7'
down_revision: Union[str, Sequence[str], None] = 'bee2be49ce3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedd_generation_started', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('embedd_generation_ended', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('embedd_deletion_started', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('embedd_deletion_ended', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedd_deletion_ended')
    op.drop_column('documents', 'embedd_deletion_started')
    op.drop_column('documents', 'embedd_generation_ended')
    op.drop_column('documents', 'embedd_generation_started')
    # ### end Alembic commands ###
