"""add_original_file_path_and_file_size_to_documents

Revision ID: 84e3ff563270
Revises: 7c8762e95da7
Create Date: 2026-09-29 16:37:45.444989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84e3ff563270'
down_revision: Union[str, Sequence[str], None] = '7c8762e95da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_file_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.alter_column('documents', 'embedded',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('embedding_jobs', 'status',
               existing_type=mysql.ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED'),
               nullable=False)
    op.alter_column('embedding_jobs', 'progress',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('embedding_jobs', 'embedded_chunks',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('embedding_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('embedding_jobs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding_jobs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('embedding_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('embedding_jobs', 'embedded_chunks',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('embedding_jobs', 'progress',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('embedding_jobs', 'status',
               existing_type=mysql.ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED'),
               nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'embedded',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_file_path')
    # ### end Alembic commands ###
