"""add_embedding_state_and_chunks_fields_to_documents

Revision ID: bee2be49ce3d
Revises: 84e3ff563270
Create Date: 2026-09-29 17:03:58.038031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bee2be49ce3d'
down_revision: Union[str, Sequence[str], None] = '84e3ff563270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('generating_embedding', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('deleting_embedding', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('total_chunks', sa.BigInteger(), nullable=False))
    op.alter_column('documents', 'embedded',
               existing_type=mysql.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'embedded',
               existing_type=sa.Boolean(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'deleting_embedding')
    op.drop_column('documents', 'generating_embedding')
    # ### end Alembic commands ###
